/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade02.view;

/**
 *
 * @author USER
 */
public class TelaAdvinheOnumeroDoGenio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAdvinheOnumeroDoGenio.class.getName());

    /**
     * Creates new form TelaAdvinheOnumeroDoGenio
     */
    public TelaAdvinheOnumeroDoGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnnumero = new javax.swing.JSpinner();
        btnadivinhe = new javax.swing.JButton();
        lblresult = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblballon_result = new javax.swing.JLabel();
        lblimage_genio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spnnumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(spnnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, -1));

        btnadivinhe.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnadivinhe.setForeground(new java.awt.Color(0, 0, 204));
        btnadivinhe.setText("ADVINHE");
        btnadivinhe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadivinheActionPerformed(evt);
            }
        });
        getContentPane().add(btnadivinhe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, -1));

        lblresult.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        lblresult.setForeground(new java.awt.Color(255, 255, 255));
        lblresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblresult.setText("Vou pensar em um número entre 1 e 5,\n tente adivinhar");
        getContentPane().add(lblresult, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 370, 50));

        jLabel1.setText("Selecione um número");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblballon_result.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblballon_result.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade02/image/balaoDeFala1.png"))); // NOI18N
        getContentPane().add(lblballon_result, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, -20, -1, 200));

        lblimage_genio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade02/image/genio.png"))); // NOI18N
        getContentPane().add(lblimage_genio, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 230, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnadivinheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadivinheActionPerformed
        // TODO add your handling code here:
        lblresult.setText("Vou pensar em um número de 1 a 5, tente adivinhar!");
         spnnumero.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
         int numero = (int) spnnumero.getValue();
         
         int numeroAleatorio = (int) (1 + Math.random()* 5);
         
         if(numero == numeroAleatorio){
             lblresult.setText("Você Acertou");
         }else{
             lblresult.setText("Você Errou, eu pensei no " +numeroAleatorio);
         }
    }//GEN-LAST:event_btnadivinheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAdvinheOnumeroDoGenio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadivinhe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblballon_result;
    private javax.swing.JLabel lblimage_genio;
    private javax.swing.JLabel lblresult;
    private javax.swing.JSpinner spnnumero;
    // End of variables declaration//GEN-END:variables
}
