/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade01.view;

/**
 *
 * @author USER
 */
public class TelaCalculadora extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaCalculadora.class.getName());

    /**
     * Creates new form TelaCalculadora
     */
    public TelaCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblData_de_nascimento = new javax.swing.JLabel();
        txtDia = new javax.swing.JTextField();
        btnCalcularIdade = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblIdade_show = new javax.swing.JLabel();
        lblCalendar_image = new javax.swing.JLabel();
        lblImage_profile = new javax.swing.JLabel();
        lblDia = new javax.swing.JLabel();
        lblMes = new javax.swing.JLabel();
        txtMes = new javax.swing.JTextField();
        lblAno = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        lblTratamento_de_erros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblData_de_nascimento.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblData_de_nascimento.setForeground(new java.awt.Color(255, 0, 0));
        lblData_de_nascimento.setText("Informe sua data de nascimento:");
        getContentPane().add(lblData_de_nascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 230, 30));

        txtDia.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        txtDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaActionPerformed(evt);
            }
        });
        getContentPane().add(txtDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 50, -1));

        btnCalcularIdade.setBackground(new java.awt.Color(255, 0, 0));
        btnCalcularIdade.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCalcularIdade.setForeground(new java.awt.Color(255, 255, 255));
        btnCalcularIdade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade01/image/calculate_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btnCalcularIdade.setText("CALCULAR ");
        btnCalcularIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularIdadeActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcularIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 140, 40));

        lblResultado.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 220, 30));

        lblIdade_show.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblIdade_show.setText("IDADE");
        getContentPane().add(lblIdade_show, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 60, 30));

        lblCalendar_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade01/image/calendar_today_24dp_EA3323_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        getContentPane().add(lblCalendar_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, 20));

        lblImage_profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade01/image/image_perfil.png"))); // NOI18N
        getContentPane().add(lblImage_profile, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 110, 110));

        lblDia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDia.setText("DIA");
        getContentPane().add(lblDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lblMes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMes.setText("MÊS");
        getContentPane().add(lblMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        txtMes.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        txtMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMesActionPerformed(evt);
            }
        });
        getContentPane().add(txtMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 50, -1));

        lblAno.setText("ANO");
        getContentPane().add(lblAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        txtAno.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        getContentPane().add(txtAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 60, -1));

        lblTratamento_de_erros.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTratamento_de_erros.setForeground(new java.awt.Color(255, 0, 0));
        lblTratamento_de_erros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblTratamento_de_erros, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 220, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtDiaActionPerformed

    private void btnCalcularIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularIdadeActionPerformed
        // TODO add your handling code here:
        int dia = Integer.parseInt(txtDia.getText()); 
        int mes = Integer.parseInt(txtMes.getText());
        int ano = Integer.parseInt(txtAno.getText()); 
        
        java.time.LocalDate hoje = java.time.LocalDate.now(); //Recebe a data atual
        
        //Tratamento de erros, se a data inserida for com valores inválidos
        if(dia > 31 || dia < 1 || mes > 12 || mes < 1 || ano > hoje.getYear() || ano < 1905){
            lblTratamento_de_erros.setText("Informe uma data válida");
            return;
        }else{
            //Se a próxima data inserida for válida ele "limpa" a mensagem de erro
            lblTratamento_de_erros.setText(" ");
        }
        
        int anoAtual = java.time.Year.now().getValue(); //Recebe o ano atual 
        int resultadoIdade = anoAtual - ano;
        
        //Se o usuário ainda não completou a idade anual, o resultado é diminuido (-1)
        if(mes > hoje.getMonthValue() || mes == hoje.getMonthValue() && dia > hoje.getDayOfMonth()){
            resultadoIdade = resultadoIdade - 1; 
            if(resultadoIdade < 0){ 
                lblTratamento_de_erros.setText("Data inválida");
                lblResultado.setText(" ");
                return;
            }else
                lblTratamento_de_erros.setText(" ");
        }
        lblResultado.setText(resultadoIdade + " anos");
    }//GEN-LAST:event_btnCalcularIdadeActionPerformed

    private void txtMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCalculadora().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularIdade;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblCalendar_image;
    private javax.swing.JLabel lblData_de_nascimento;
    private javax.swing.JLabel lblDia;
    private javax.swing.JLabel lblIdade_show;
    private javax.swing.JLabel lblImage_profile;
    private javax.swing.JLabel lblMes;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTratamento_de_erros;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    // End of variables declaration//GEN-END:variables
}
