/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade06;

/**
 *
 * @author USER
 */
public class TelaFatorial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaFatorial.class.getName());

    /**
     * Creates new form TelaFatorial
     */
    public TelaFatorial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnfatorarnumero = new javax.swing.JButton();
        lblformula = new javax.swing.JLabel();
        lblresultado = new javax.swing.JLabel();
        txtinsiraumnumero = new javax.swing.JTextField();
        lblinsiraumnumero = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnfatorarnumero.setFont(new java.awt.Font("Segoe UI Black", 3, 12)); // NOI18N
        btnfatorarnumero.setText("FATORAR");
        btnfatorarnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfatorarnumeroActionPerformed(evt);
            }
        });
        getContentPane().add(btnfatorarnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 130, -1));

        lblformula.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblformula, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 20));

        lblresultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, 90, 20));
        getContentPane().add(txtinsiraumnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 150, -1));

        lblinsiraumnumero.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        lblinsiraumnumero.setText("INSIRA UM NÚMERO");
        getContentPane().add(lblinsiraumnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnfatorarnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfatorarnumeroActionPerformed
        // TODO add your handling code here:
        String numeroDigitado = txtinsiraumnumero.getText();
        int numeroInseridoParaFatorar = Integer.parseInt(numeroDigitado);
        Fatorial fatorarObj = new Fatorial();
        fatorarObj.setValor(numeroInseridoParaFatorar);
        lblformula.setText(fatorarObj.getFormula());
        lblresultado.setText(Integer.toString(fatorarObj.getResultado()));
    }//GEN-LAST:event_btnfatorarnumeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaFatorial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfatorarnumero;
    private javax.swing.JLabel lblformula;
    private javax.swing.JLabel lblinsiraumnumero;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JTextField txtinsiraumnumero;
    // End of variables declaration//GEN-END:variables
}
