/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade05.view;

/**
 *
 * @author USER
 */
public class TelaRepeticaoComSlider extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRepeticaoComSlider.class.getName());

    /**
     * Creates new form TelaRepeticaoComSlider
     */
    public TelaRepeticaoComSlider() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblinicio = new javax.swing.JLabel();
        lblfim = new javax.swing.JLabel();
        lblpasso = new javax.swing.JLabel();
        sldvalorminimo = new javax.swing.JSlider();
        sldvalormaximo = new javax.swing.JSlider();
        sldvalorstep = new javax.swing.JSlider();
        txtresultado = new javax.swing.JScrollPane();
        txtvalorescontados = new javax.swing.JTextArea();
        btncontarnumeros = new javax.swing.JButton();
        lblaviso = new javax.swing.JLabel();
        lblminimo = new javax.swing.JLabel();
        lblvalormaximo = new javax.swing.JLabel();
        lblvalorstep = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblinicio.setText("INICIO");
        getContentPane().add(lblinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblfim.setText("FIM");
        getContentPane().add(lblfim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblpasso.setText("PASSO");
        getContentPane().add(lblpasso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        sldvalorminimo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldvalorminimoStateChanged(evt);
            }
        });
        getContentPane().add(sldvalorminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        sldvalormaximo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldvalormaximoStateChanged(evt);
            }
        });
        getContentPane().add(sldvalormaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        sldvalorstep.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldvalorstepStateChanged(evt);
            }
        });
        getContentPane().add(sldvalorstep, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtvalorescontados.setColumns(20);
        txtvalorescontados.setRows(5);
        txtresultado.setViewportView(txtvalorescontados);

        getContentPane().add(txtresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, 250));

        btncontarnumeros.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btncontarnumeros.setForeground(new java.awt.Color(0, 204, 204));
        btncontarnumeros.setText("CONTAR");
        btncontarnumeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncontarnumerosActionPerformed(evt);
            }
        });
        getContentPane().add(btncontarnumeros, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, -1, -1));

        lblaviso.setForeground(new java.awt.Color(255, 0, 0));
        lblaviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblaviso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblaviso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 390, 20));

        lblminimo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblminimo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 40, 20));

        lblvalormaximo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblvalormaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 40, 20));

        lblvalorstep.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblvalorstep, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncontarnumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncontarnumerosActionPerformed
        // TODO add your handling code here:
        int minimo = sldvalorminimo.getValue();
        int maximo = sldvalormaximo.getValue();
        int step = sldvalorstep.getValue();
        
        lblaviso.setText(" ");
        if(minimo > maximo){
            lblaviso.setText("Valor minimo não pode ser maior, tente novamente");
            return;
        }
        
        StringBuilder string = new StringBuilder();
        for(int i = minimo; i <= maximo; i += step){
            string.append(i).append("\n"); //adiciona um número na sequência da string e pula uma linha
        }
        
        txtvalorescontados.setText(string.toString());
    }//GEN-LAST:event_btncontarnumerosActionPerformed

    private void sldvalorminimoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldvalorminimoStateChanged
        // TODO add your handling code here:
        lblminimo.setText(" " + sldvalorminimo.getValue());
    }//GEN-LAST:event_sldvalorminimoStateChanged

    private void sldvalormaximoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldvalormaximoStateChanged
        // TODO add your handling code here:
        lblvalormaximo.setText(" " + sldvalormaximo.getValue());
    }//GEN-LAST:event_sldvalormaximoStateChanged

    private void sldvalorstepStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldvalorstepStateChanged
        // TODO add your handling code here:
        lblvalorstep.setText(" " + sldvalorstep.getValue());
    }//GEN-LAST:event_sldvalorstepStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRepeticaoComSlider().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncontarnumeros;
    private javax.swing.JLabel lblaviso;
    private javax.swing.JLabel lblfim;
    private javax.swing.JLabel lblinicio;
    private javax.swing.JLabel lblminimo;
    private javax.swing.JLabel lblpasso;
    private javax.swing.JLabel lblvalormaximo;
    private javax.swing.JLabel lblvalorstep;
    private javax.swing.JSlider sldvalormaximo;
    private javax.swing.JSlider sldvalorminimo;
    private javax.swing.JSlider sldvalorstep;
    private javax.swing.JScrollPane txtresultado;
    private javax.swing.JTextArea txtvalorescontados;
    // End of variables declaration//GEN-END:variables
}
