/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade09;

/**
 *
 * @author USER
 */
public class ViewPagamentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewPagamentos.class.getName());

    /**
     * Creates new form ViewPagamentos
     */
    public ViewPagamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbpagamentos = new javax.swing.JComboBox<>();
        lblpagamento = new javax.swing.JLabel();
        lblvalor = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        lblresultado = new javax.swing.JLabel();
        lblmetodos = new javax.swing.JLabel();
        lblrecibo = new javax.swing.JLabel();
        lblmostrarrecibo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbpagamentos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dinheiro", "Cartão", "PIX", " " }));
        cmbpagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpagamentosActionPerformed(evt);
            }
        });
        getContentPane().add(cmbpagamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 90, 30));

        lblpagamento.setText("Selecione o tipo de pagamento");
        getContentPane().add(lblpagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lblvalor.setText("Informe o valor ");
        getContentPane().add(lblvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));
        getContentPane().add(txtvalor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 140, -1));

        lblresultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblresultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 80, 30));

        lblmetodos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblmetodos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblmetodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 230, 20));

        lblrecibo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblrecibo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblrecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 380, 50));

        lblmostrarrecibo.setText("RECIBO");
        lblmostrarrecibo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(lblmostrarrecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbpagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpagamentosActionPerformed
        // TODO add your handling code here:
         double valorinserido = Double.parseDouble(txtvalor.getText());
       String pagamento_selecionado = cmbpagamentos.getSelectedItem().toString();
       if(pagamento_selecionado.equals("Dinheiro")){
           PagamentoDinheiro pagamentoemdinheiro = new PagamentoDinheiro();
           String valordinheiro = Double.toString(pagamentoemdinheiro.calcularTotal(valorinserido));
           lblresultado.setText(valordinheiro);
           lblmetodos.setText("Valo com desconto");
           lblrecibo.setText(pagamentoemdinheiro.imprimirRecibo(valorinserido));
       }else if (pagamento_selecionado.equals("Cartão")){
           PagamentoCartao pagamentoemcartao = new PagamentoCartao();
           String valorcartao = Double.toString(pagamentoemcartao.calcularTotal(valorinserido));
           lblresultado.setText(valorcartao);
           lblmetodos.setText("Valor com taxa");
           lblrecibo.setText(pagamentoemcartao.imprimirRecibo(valorinserido));
           }else if (pagamento_selecionado.equals("PIX")){
               PagamentoPix pagamentoempix = new PagamentoPix();
               String valorpix = Double.toString(pagamentoempix.calcularTotal(valorinserido));
               lblresultado.setText(valorpix);
               lblmetodos.setText("Valor de cashback");
               lblrecibo.setText(pagamentoempix.imprimirRecibo(valorinserido));
           }

    }//GEN-LAST:event_cmbpagamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewPagamentos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbpagamentos;
    private javax.swing.JLabel lblmetodos;
    private javax.swing.JLabel lblmostrarrecibo;
    private javax.swing.JLabel lblpagamento;
    private javax.swing.JLabel lblrecibo;
    private javax.swing.JLabel lblresultado;
    private javax.swing.JLabel lblvalor;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
